# Generated by Django 4.2.7 on 2023-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytestmodel',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
